Repository DeveloperRyou/ft_irc, pull requests merged in 2023-05, with the labels that each got.

#9 Client.hpp Client.cpp 작성
  include/Client.hpp
  src/Client.cpp
Labels: enhancement

#16 Feature/#8 channel 객체 만들기
  Makefile
  include/Channel.hpp
  include/ft_irc.hpp
  src/Channel.cpp
Labels: enhancement

#18 Channel.hpp err fixed & parameter modifed
  include/Channel.hpp
  src/Channel.cpp
Labels: bug

#21 Add getClient, getChannel, Server constructor redifine
  include/Server.hpp
  include/ft_irc.hpp
  src/Server.cpp
Labels: bug, enhancement

#22 create method of server
  include/Server.hpp
  src/Server.cpp
Labels: enhancement

#23 parser draft
  include/Parser.hpp
  include/ft_irc.hpp
  src/Parser.cpp
Labels: enhancement

#30 add prefix
  include/Server.hpp
  src/Server.cpp
Labels: enhancement

#28 channel벡터 삭제 및 getPrefix() 추가
  include/Client.hpp
  src/Client.cpp
Labels: enhancement, wontfix

#31 Feature/#29 channelmode 객체 만들기
  Makefile
  include/ChannelMode.hpp
  include/ft_irc.hpp
  src/ChannelMode.cpp
Labels: enhancement, wontfix

#27 Feature/#8 channel 객체 만들기
  include/Channel.hpp
  include/ft_irc.hpp
  src/Channel.cpp
Labels: question, wontfix
