Repository DeveloperRyou/ft_irc, pull requests merged in 2023-06, with the labels that each got.

#38 Feature/#36 channel 메시지 리팩토링
  include/Channel.hpp
  include/Server.hpp
  include/ft_irc.hpp
  src/Channel.cpp
  src/ChannelMode.cpp
  src/Server.cpp
Labels: refactoring

#37 Channel Info Class 생성
  Makefile
  include/Channel.hpp
  include/ChannelInfo.hpp
  include/ChannelMode.hpp
  include/ClientMode.hpp
  include/ft_irc.hpp
  src/Channel.cpp
  src/ChannelInfo.cpp
  src/ChannelMode.cpp
  src/ClientMode.cpp
  src/Server.cpp
Labels: refactoring

#40 cpp11~ & Makefile & changeLimitMode 수정
  Makefile
  include/ft_irc.hpp
  src/ChannelMode.cpp
  src/main.cpp
Labels: refactoring

#46 Client 접속 기능 구체화, Channel 생성시 인자 재정의
  include/Channel.hpp
  include/ChannelInfo.hpp
  include/Client.hpp
  include/Server.hpp
  src/Channel.cpp
  src/ChannelInfo.cpp
  src/Client.cpp
  src/Parser.cpp
  src/Server.cpp
Labels: refactoring

#47 Feature/#43 parser 수정
  include/Channel.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Parser.cpp
Labels: wontfix

#49 Bug 수정
  include/Channel.hpp
  include/ChannelInfo.hpp
  include/Client.hpp
  include/Parser.hpp
  include/Server.hpp
  src/Channel.cpp
  src/ChannelInfo.cpp
  src/ChannelMode.cpp
  src/Client.cpp
  src/Parser.cpp
  src/Server.cpp
  src/main.cpp
Labels: bug
